# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'testingwindow1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from classifiers import  Ui_Form
from subprocess import call

class Ui_testingForm(object):
    def openclassifiers(self):
        self.Widget=QtWidgets.QWidget()
        self.text1 = self.textEdit.toPlainText()
        self.ui=Ui_Form(self.text1)
        self.ui.setupUi(self.Widget)
        self.Widget.show()
       
        
    def setupUi(self, testingForm):
        testingForm.setObjectName("testingForm")
        testingForm.resize(740, 605)
        self.label = QtWidgets.QLabel(testingForm)
        self.label.setGeometry(QtCore.QRect(0, 0, 751, 611))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("test2.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(testingForm)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 341, 41))
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(testingForm)
        self.pushButton.setGeometry(QtCore.QRect(270, 500, 181, 61))
        self.pushButton.setStyleSheet("")
        self.pushButton.setCheckable(False)
        self.pushButton.setAutoRepeat(False)
        self.pushButton.setAutoDefault(False)
        self.pushButton.setDefault(False)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(testingForm)
        self.textEdit.setGeometry(QtCore.QRect(50, 80, 621, 401))
        self.textEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.textEdit.setObjectName("textEdit")

        self.retranslateUi(testingForm)
        QtCore.QMetaObject.connectSlotsByName(testingForm)
        self.pushButton.clicked.connect(self.openclassifiers)

    def retranslateUi(self, testingForm):
        _translate = QtCore.QCoreApplication.translate
        testingForm.setWindowTitle(_translate("testingForm", "Testing Form"))
        self.label_2.setText(_translate("testingForm", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600; font-style:italic; color:#ffbeb7;\">TESTING WINDOW</span></p></body></html>"))
        self.pushButton.setText(_translate("testingForm", "Predict"))
        self.textEdit.setHtml(_translate("testingForm", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Enter the text / Copy the text</p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    testingForm = QtWidgets.QWidget()
    ui = Ui_testingForm()
    ui.setupUi(testingForm)
    testingForm.show()
    sys.exit(app.exec_())
